// <auto-generated />
namespace Modelo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201610252234147_1 schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
